version: "3.8"
services:
  tritonserver:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "127.0.0.1:8003:8000"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8002:8002"
    volumes:
      - ./model_repository:/models
    command: tritonserver --model-repository=/models --http-thread-count 8 --log-verbose 0 --log-error 1 --log-info 1
